### ISSUE TITLE
Getting 3 different errors (-2, -1, and 2) when initialize an agent

### ISSUE THREAD

**Issue by smasoudn** [Dynatrace/OneAgent-SDK-for-Python#19]
Hi,

I am getting three different errors when I run from a command line, when I initialize an agent inside a python script and when I run the command on a Mac (as opposed to Linux):

Command line:

    $ python -c "import oneagent; print(oneagent.initialize())"
    InitResult(status=-1, error=SDKError(-1342308345, 'onesdk_initialize_2: Could not load agent.'))

Python script

    >> import oneagent
    >> oneagent.initialize()
    InitResult(status=2, error=None)

On Mac (no matter how many times I force to re-install):

    InitResult(status=-2, error=SDKError(-1342308345, 'Failed loading SDK stub from /Users/mnosrat/Projects/miniconda3/lib/python3.7/site-packages/oneagent/_impl/native/libonesdk_shared.so: "dlopen(/Users/mnosrat/Projects/miniconda3/lib/python3.7/site-packages/oneagent/_impl/native/libonesdk_shared.so, 6): image not found". Check your installation of the oneagent-sdk Python package, e.g., try running `pip install --verbose --force-reinstall oneagent-sdk`.'))

Any idea how I can fix this?
Thanks a lot

**Comment by arminru** [comment]
Hi @smasoudn!

Please have a look at the https://github.com/Dynatrace/OneAgent-SDK-for-Python#requirements section. The OneAgent SDK for Python wraps around the OneAgent SDK for C/C++, which in turn depends on the Dynatrace OneAgent. Supported platforms and OneAgent versions are mentioned there: https://github.com/Dynatrace/OneAgent-SDK-for-C#requirements
Do you have a working Dynatrace OneAgent installation on your machine? Please note that the OneAgent is _not_ available on MacOS and therefore neither the SDK for Python nor C/C++ will work there.

**Comment by Oberon00** [comment]
As @arminru said, for your first example, it looks like you do not have the OneAgent (which is not included in the SDK but must be downloaded from your Dynatrace environment) installed.

For your second example 2 is STATUS_ALREADY_INITIALIZED: https://github.com/Dynatrace/OneAgent-SDK-for-Python/blob/v1.3.0/src/oneagent/__init__.py#L103 The SDK won't even attempt to initialize itself again if you don't call shutdown the same number of times, so you probably ran this code more than one time in the same Python interpreter.

For your third example, the native part of the SDK is not available on MacOS, so this is the expected behavior. You can still run applications instrumented with the OneAgent SDK for Python on MacOS, but the SDK methods will do nothing.

**Comment by arminru** [comment]
Hi @smasoudn,
seems like your issue is resolved. If you need any further help, feel free to reopen.
